### PR TITLE
Reworking of CodeMatcher refactor from @house9, originally #13

### PR DESCRIPTION
**Pull request by joonty**
In #13, @house9 submitted lots of changes, including a refactor of the code matching into a separate class, `CodeMatcher`. At around the same time, @avdi moved many of the core files to make it mountable on a rails app. This meant that #13 was no longer automatically merge-able, so this is a manual merge and tidy up.

There are no new features, just some moved files, merged conflict fixes and the fixing of a broken spec.

I've submitted it as a PR due to the size of the change. Could someone please review and test before merging into master?

Thanks.

### CODE REVIEW

**Comment by bf4** [comment]
I'll take a look at it.

**Comment by joonty** [comment]
Thanks a lot. Unfortunately, it's no longer automatically mergeable :unamused: 

However, it shouldn't be too tricky to merge it via the command line.

**Comment by bf4** [comment]
I've resolved the conflicts locally. On this project, because I'm manually testing each merge, I'm doing all of them on the command line :)

**Comment by bf4** [comment]
So, right now app.rb is in two places.. Oh I see. a little confusing

**Comment by rwjblue** [comment]
Looks like `./app.rb` is requiring `lib/ppwm_matcher/app.rb`. I could be wrong...

**Comment by bf4** [comment]
I'll merge it now unless you have any other thoughts. I only added a log/.gitkeep since it was trying to log to that dir and it wasn't there

**Comment by avdi** [comment]
I know, I know. "What was @avdi thinking?!"

I had to get the app into a namespaced dir in lib/. In order to to avoid
having to fix the rackup file as well, I kept the top-level app.rb around
as a stub. I also wound up moving some stuff out of the namespaced app.rb
that was incompatible with running under Rails.

I wouldn't be opposed to seeing one of these files renamed.

**Comment by avdi** [comment]
On Thu, Jun 13, 2013 at 9:42 AM, Benjamin Fleischer <
notifications@github.com> wrote:

> I only added a log/.gitkeep since it was trying to log to that dir and it
> wasn't there

Crap, sorry.

**Comment by rwjblue** [comment]
@bf4 I also added a .gitkeep in #17.  I'll refactor once this is merged.

**Comment by bf4** [comment]
@avdi I jut didn't expect the old one to use the new one.. :)  Anyhow, once this is merged, you should be able to just

```
mount PpwmMatcher::App, :at => 'match'
```

and add to the Gemfile

```
gem 'ppwm-matcher', require: 'ppwm-matcher/app', github: 'rubyrogues/ppwm-matcher'
```

**Pull request merged**
