### PR TITLE
First crack at gemification and railtying

### PR DESCRIPTION
**Pull request by bf4**
This is a work in progress or first step.. let me know if you want to take it from here and finish it.. I'm not sure if I'll be putting more time into it right now

re: https://github.com/rubyrogues/ppwm-matcher/issues/1

### CODE REVIEW

**Comment by bf4** [comment]
This doesn't handle migrations, routing, or github configuration.. it has a basic skeleton of an engine and railtie that don't do anything

**Comment by avdi** [comment]
I probably won't have time before I leave... @joonty want to take a look when you're back?

**Comment by bf4** [comment]
Does anyone know @josevalim ?  I believe he did some of this in his Crafting Rails book.

**Comment by avdi** [comment]
Help us @josevalim, you're our only hope! ;-)

And yeah, that book has the answers I believe, and if I had any time at all I'd be cracking it open right now...

**Comment by bf4** [comment]
I was also thinking that the [new relic rpm gem does this in developer mode](https://github.com/newrelic/rpm/blob/master/lib/new_relic/control/frameworks/rails.rb#L99) as middleware

```
require 'new_relic/rack/developer_mode'
rails_config.middleware.use NewRelic::Rack::DeveloperMode
```

[It looks like it just intercepts the '/new_relic' request](https://github.com/newrelic/rpm/blob/master/lib/new_relic/rack/developer_mode.rb#L28)

```
def call(env)
  return @app.call(env) unless /^\/newrelic/ =~ ::Rack::Request.new(env).path_info
  dup._call(env)
end
```

**Comment by joonty** [comment]
Hey guys, I'll definitely take a look at this tomorrow (GMT), if it hasn't already been sorted. Good stuff so far!

**Comment by avdi** [comment]
Possibly of note: https://github.com/airblade/paper_trail/tree/master/lib/generators/paper_trail

**Comment by avdi** [comment]
I guess the usual way to do this for plugins is to have a generator that copies in the migrations, rather than simply running the migrations from the gem. Which bugs me slightly but there's probably a good reason for it, probably having to do with the timestamps.

**Comment by UnderpantsGnome** [comment]
Have a look at #6 it does just enough to bring in migrations. I didn't want to make a mess in here. You can accept that pull or just grab the bits out, it's pretty trivial.

**Comment by bf4** [comment]
Ok, [this is how split does it](https://github.com/andrew/split#web-interface) where [Split::Dashboard is just a sinatra app like our PpwmMatcher::App](https://github.com/andrew/split/blob/master/lib/split/dashboard.rb)

```
mount Split::Dashboard, :at => 'split'
```

**Comment by avdi** [comment]
Interesting! I did it with a leading slash when testing it.

And boy, the Sinatra Github auth extension was _not_ friendly to getting
that to work. I think the /unauthenticated path might still be broken.

**Comment by josevalim** [comment]
How can I help?

**Comment by josevalim** [comment]
> I guess the usual way to do this for plugins is to have a generator that copies in the migrations, rather than simply running the migrations from the gem. Which bugs me slightly but there's probably a good reason for it, probably having to do with the timestamps.

If it is an engine, the engine migrations will be copied automatically as long as they are also placed on `db/migrate`.

**Comment by avdi** [comment]
On Thu, Jun 13, 2013 at 9:45 AM, José Valim notifications@github.comwrote:

> If it is an engine, the engine migrations will be copied automatically as
> long as they are also placed on db/migrate.

What qualifies it as an engine? Does it have to have the whole Rails
shebang - controllers, etc? We just have a mountable Sinatra app.

## 

Avdi Grimm
http://avdi.org

I only check email twice a day. to reach me sooner, go to
http://awayfind.com/avdi

**Comment by josevalim** [comment]
[This file](https://github.com/rubyrogues/ppwm-matcher/blob/master/lib/ppwm_matcher/engine.rb) makes it an engine. However this file needs to be required when the gem is required. So you may want to add something like `require "ppwm_matcher/engine" if defined?(Rails)` to `lib/ppwm_matcher.rb` or simply instruct developers to require the engine file before their Rails Application definition in `config/application.rb`.

**Comment by avdi** [comment]
@josevalim nice! Thanks for clarifying that, it's something I'd been unclear on for a while.

When you say the migrations will be "copied automatically", at what point does that happen?

And just to clear up my curiosity, would you mind explaining when to define a migrations generator (as I've done in the generators dir) vs. when to make an engine and have migrations copied automatically?

**Comment by josevalim** [comment]
I am sorry. The migrations won't be copied automatically, instead we provide a rake task that copies them. Search for migrations on the [Rails::Engine docs page](http://edgeapi.rubyonrails.org/classes/Rails/Engine.html). Also, you changed the engine name to be `ppwm-matcher` which means that's what you will type in the rake command.

There is a configuration you could use to make the application automatically run all the migrations from an engine. In your `config/application.rb`, you can add:

``` ruby
config.paths["db/migrate"] += PpwmMatcher::Engine.paths["db/migrate"].existent
```

The code adds the engine's db/migrate path to the application migrations path.

Copying with the rake task is useful when you want to explicitly control the migrations you copy from an engine. The configuration above is useful when you trust and own the engine and want all migrations in the engine to run automatically. I particularly use it when extracting application functionalities into isolated engines.

> And just to clear up my curiosity, would you mind explaining when to define a migrations generator (as I've done in the generators dir) vs. when to make an engine and have migrations copied automatically?

I would use a generator whenever the migrations are dynamic. For example, Devise does that since you can have a migration for a User model, an Admin model, whatever you come up with. In this plugin's case though, the migration is "static", so I would just copy using the rake tasks or the configuration above.

**Comment by bf4** [comment]
See https://github.com/avdi/ppwm/pull/31 which has the following issues

1) needs github configuration
2) needs the migrations
3) needs to change the callback path to be under '/match' 
4) handle assets intelligently, whether loading its own or using them from the parent app

**Comment by bf4** [comment]
Also, @josevalim just wanted to ensure we all know this PR won't be used, as we've since pulled in similar code.

**Comment by UnderpantsGnome** [comment]
@bf4 has any progress been made, did you still want to pair, should I just take a run at it?

**Comment by bf4** [comment]
So, I haven't done anything here. I'm happy to pair over your shoulder for a second set of eyes, but otherwise I'm working now and need to get a certain amount done before I leave for rubynation / dc. Lemme know if that's fine. @rjackson and I used wemux and vim last night.  He recommended https://github.com/chrishunt/github-auth but we didn't use it.

**Comment by bf4** [comment]
- where here I think most importantly means the migrations since the the github api can be set in the env and maybe set the assets to use relative paths for now (and update the callback path)

**Comment by bf4** [comment]
So, so the integration is mostly done now https://github.com/avdi/ppwm/pull/31 I'm going to close this

**Comment by UnderpantsGnome** [comment]
@bf4 I wont be available until later in the day and I'm guessing you will be headed to DC. If the issues are current, I can swing back around and see what needs to be done later. Enjoy DC.

**Pull request closed without merging**
